<a href="https://colab.research.google.com/github/mnrkvalli/Text_Autocomplete/blob/main/TextAutocomplete.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

# Reading corpus the text file
with open("mytext.txt", 'r', encoding='utf-8') as myfile:
    mytext = myfile.read()

In [2]:
mytext

'\'Following a lavish state visit by Indian Prime Minister Narendra Modi to Washington, US President Joe Biden has called his country\\\'s partnership with India among the "most consequential in the world". The BBC\\\'s Vikas Pandey and Soutik Biswas explore the factors that contribute to the visit\\\'s potential in strengthening the ties between the two nations.\\n\\nThe US\\\'s relationship with India - the world\\\'s most populous country - is "stronger, closer and more dynamic than any time in history", Mr Biden said at the completion of a pomp-filled state visit by Mr Modi to the White House.\\n\\nThe remark may not be an exaggeration. "This summit suggests that the relationship has been transformed. It underscores just how broad and deep it has become in a relatively short time," says Michael Kugelman of The Wilson Center, an American think-tank.\\n\\nA key reason is that Washington is keen to draw India closer so that it can act as a counterbalance to China\\\'s growing influenc

In [3]:
mytokenizer = Tokenizer()
mytokenizer.fit_on_texts([mytext])
total_words = len(mytokenizer.word_index) + 1

In [4]:
mytokenizer.word_index

{'the': 1,
 'to': 2,
 'india': 3,
 'in': 4,
 'a': 5,
 'and': 6,
 'of': 7,
 "'s": 8,
 'n': 9,
 'mr': 10,
 'modi': 11,
 'us': 12,
 'is': 13,
 'has': 14,
 'that': 15,
 'biden': 16,
 'washington': 17,
 'it': 18,
 'as': 19,
 'with': 20,
 'not': 21,
 'for': 22,
 'on': 23,
 'an': 24,
 'says': 25,
 'will': 26,
 'are': 27,
 'visit': 28,
 'indian': 29,
 'prime': 30,
 'minister': 31,
 'nthe': 32,
 'china': 33,
 'have': 34,
 'trade': 35,
 'by': 36,
 'relationship': 37,
 'this': 38,
 'been': 39,
 'about': 40,
 'strategic': 41,
 'president': 42,
 'more': 43,
 'up': 44,
 'during': 45,
 'also': 46,
 'make': 47,
 'sirohi': 48,
 'nbut': 49,
 'air': 50,
 'force': 51,
 'they': 52,
 'state': 53,
 'his': 54,
 'world': 55,
 'ties': 56,
 'two': 57,
 'at': 58,
 'white': 59,
 'house': 60,
 'be': 61,
 'lot': 62,
 'technology': 63,
 'jet': 64,
 'but': 65,
 'semiconductor': 66,
 'now': 67,
 'first': 68,
 '2023': 69,
 'administration': 70,
 'was': 71,
 'global': 72,
 'one': 73,
 'he': 74,
 'without': 75,
 'narendra

In [5]:
my_input_sequences = []
for line in mytext.split('\n'):
    #print(line)
    token_list = mytokenizer.texts_to_sequences([line])[0]
    #print(token_list)
    for i in range(1, len(token_list)):
        my_n_gram_sequence = token_list[:i+1]
        #print(my_n_gram_sequence)
        my_input_sequences.append(my_n_gram_sequence)
        #print(input_sequences)

In [6]:
max_sequence_len = max([len(seq) for seq in my_input_sequences])
input_sequences = np.array(pad_sequences(my_input_sequences, maxlen=max_sequence_len, padding='pre'))

In [7]:
input_sequences[1]

array([  0,   0,   0, ..., 178,   5, 179], dtype=int32)

In [8]:
X = input_sequences[:, :-1]
y = input_sequences[:, -1]

In [9]:
X[1]

array([  0,   0,   0, ...,   0, 178,   5], dtype=int32)

In [10]:
y

array([  5, 179,  53, ...,  92,  48,  89], dtype=int32)

In [11]:
y = np.array(tf.keras.utils.to_categorical(y, num_classes=total_words))

In [12]:
y[1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [13]:
model = Sequential()
model.add(Embedding(total_words, 100, input_length=max_sequence_len-1))
model.add(LSTM(150))
model.add(Dense(total_words, activation='softmax'))
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 1461, 100)         60300     
                                                                 
 lstm (LSTM)                 (None, 150)               150600    
                                                                 
 dense (Dense)               (None, 603)               91053     
                                                                 
Total params: 301953 (1.15 MB)
Trainable params: 301953 (1.15 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [14]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=100, verbose=1)

Epoch 1/100
46/46 [==============================] - 123s 3s/step - loss: 6.1336 - accuracy: 0.0493
Epoch 2/100
46/46 [==============================] - 119s 3s/step - loss: 5.7679 - accuracy: 0.0548
Epoch 3/100
46/46 [==============================] - 120s 3s/step - loss: 5.6872 - accuracy: 0.0548
Epoch 4/100
46/46 [==============================] - 120s 3s/step - loss: 5.6246 - accuracy: 0.0548
Epoch 5/100
46/46 [==============================] - 117s 3s/step - loss: 5.5351 - accuracy: 0.0548
Epoch 6/100
46/46 [==============================] - 121s 3s/step - loss: 5.4102 - accuracy: 0.0575
Epoch 7/100
46/46 [==============================] - 116s 3s/step - loss: 5.2614 - accuracy: 0.0712
Epoch 8/100
46/46 [==============================] - 116s 3s/step - loss: 5.0783 - accuracy: 0.0842
Epoch 9/100
46/46 [==============================] - 117s 3s/step - loss: 4.8547 - accuracy: 0.1177
Epoch 10/100
46/46 [==============================] - 117s 3s/step - loss: 4.6251 - accuracy: 0.1362

In [15]:
input_text = "Joe biden"
predict_next_words= 6

for _ in range(predict_next_words):
    token_list = mytokenizer.texts_to_sequences([input_text])[0]
    print(token_list)
    token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
    predicted = np.argmax(model.predict(token_list), axis=-1)
    output_word = ""
    for word, index in mytokenizer.word_index.items():
        if index == predicted:
            output_word = word
            break
    input_text += " " + output_word

print(input_text)

[77, 16]
1/1 [==============================] - 1s 687ms/step
[77, 16, 24]
1/1 [==============================] - 0s 221ms/step
[77, 16, 24, 179]
1/1 [==============================] - 0s 244ms/step
[77, 16, 24, 179, 53]
1/1 [==============================] - 0s 230ms/step
[77, 16, 24, 179, 53, 28]
1/1 [==============================] - 0s 226ms/step
[77, 16, 24, 179, 53, 28, 36]
1/1 [==============================] - 0s 229ms/step
Joe biden an lavish state visit by indian


In [16]:
# Step 1: Make Predictions
predictions = model.predict(X)

# Step 2: Convert Probabilities to Class Labels
predicted_labels = np.argmax(predictions, axis=1)
true_labels = np.argmax(y,axis=1)

# Step 3: Calculate Accuracy
accuracy = np.sum(predicted_labels == true_labels) / len(true_labels)

print(f"Accuracy: {accuracy * 100:.2f}%")

46/46 [==============================] - 35s 756ms/step
Accuracy: 100.00%
